name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-07"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
JWT_SECRET = "mySecretKey"
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOThlNWFmM2EtMjUwOC00YWIzLTgwNmEtYmQ4ZTY1ZDE1OTAxIiwidGVuYW50X2lkIjoiMjA3ZGI3ODQ0MzQxZmM3ZjYwMTIyZmU0MTg5MjJiMjRiOTliOTkyODZiN2FiODE0ZTI2MTUxYjM2N2MyMWM3NiIsImludGVybmFsX3NlY3JldCI6IjkxZjlkMDZlLTBmYzgtNGQ0NS1iNTNiLWEwOTExNzVjYzkxNyJ9.YCcVA_2NrWxv0u8OFlzaNOFmPw4dl4TRaIuX7sQMZVs"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1